// src/api/types/identity-provider.ts

import { PaginatedResponse } from "./common";

/**
 * Represents a user in the system.
 */
export interface User {
  id: string;
  email: string;
  name: string;
  role: "admin" | "user" | "viewer";
  status: "active" | "inactive" | "pending";
  created_at: string;
  updated_at: string;
}

/**
 * Request payload for user login.
 */
export interface LoginRequest {
  username: string;
  password: string;
}

/**
 * Response payload for a successful login.
 */
export interface LoginResponse {
  access_token: string;
  token_type: string;
  user?: {
    id: string;
    email: string;
    full_name: string;
    category: {
      name: string;
      code: string;
      description: string;
    };
    group: {
      name: string;
      code: string;
      description: string;
      priority: number;
    };
    created_at: string;
    updated_at: string;
  };
}

/**
 * Request payload for creating a new user.
 * We omit fields that are generated by the server (id, created_at, updated_at).
 */
export interface UserCreateRequest {
  name: string;
  email: string;
  password?: string;
  role: "admin" | "user" | "viewer";
  status?: "active" | "inactive" | "pending";
}

/**
 * Request payload for updating an existing user.
 * All fields are optional.
 */
export interface UserUpdateRequest {
  name?: string;
  email?: string;
  role?: "admin" | "user" | "viewer";
  status?: "active" | "inactive";
}

/**
 * Represents a paginated list of users.
 */
export type UserListResponse = PaginatedResponse<User>;
