const fs = require("fs");
const path = require("path");

const filePath = path.join(
  __dirname,
  "..",
  "docs",
  "FRONTEND_SPLIT_SERVICE_BLUEPRINT_DETAILED_2026-07-08.md",
);

const source = fs.readFileSync(filePath, "utf8");

const standaloneSection = [
  "## 17. Target Standalone Service Bundle",
  "",
  "### 17.1 Arah Pengembangan",
  "",
  "Target jangka menengah yang inline dengan kebutuhan sekarang adalah menjadikan frontend ini sebagai:",
  "",
  "- browser-based portal",
  "- standalone deployment bundle",
  "- runtime-configurable",
  "- license-aware",
  "- service-encapsulated",
  "- siap dipakai sebelum backend benar-benar dipecah",
  "",
  "Artinya, frontend tidak lagi diposisikan sekadar aplikasi React biasa, tetapi sebagai:",
  "",
  "- **portal shell**",
  "- di atas **bootstrap runtime**",
  "- yang mengatur **service abstraction**",
  "- dan bisa dikunci oleh **license gate**",
  "",
  "### 17.2 Bentuk Arsitektur Target",
  "",
  "Lapisan target yang disarankan:",
  "",
  "1. `UI App Layer`",
  "   - CTS Portal Shell",
  "   - Connector Portal Shell",
  "   - Adapter Workspace",
  "2. `Frontend Service Layer`",
  "   - auth client",
  "   - cts client",
  "   - connector client",
  "   - adapter client",
  "   - monitoring client",
  "3. `Bootstrap Runtime Layer`",
  "   - runtime config loader",
  "   - setup status checker",
  "   - service availability checker",
  "   - public runtime config provider",
  "   - proxy logical service",
  "4. `License and Protection Layer`",
  "   - validate license key",
  "   - validate licensed host",
  "   - feature gating",
  "   - expiry / revalidation",
  "   - lock or unlock module",
  "",
  "### 17.3 Kenapa Ini Inline dengan Blueprint Existing",
  "",
  "Model ini tidak bertabrakan dengan blueprint sebelumnya. Justru melengkapi:",
  "",
  "- split shell tetap dipakai",
  "- adapter workspace tetap dipakai",
  "- logical service split jadi lebih formal",
  "- runtime config jadi gerbang sebelum app init",
  "- licensing memberi lapisan kontrol tanpa mengacak feature module",
  "",
  "### 17.4 Prinsip Wajib",
  "",
  "- FE tidak boleh tahu angka port deployment sebagai identitas bisnis",
  "- runtime config harus selesai di-load sebelum auth init",
  "- license validation final tidak boleh ditaruh murni di browser",
  "- feature gating harus dibaca dari runtime/license state",
  "- module ownership tidak boleh campur kembali",
  "- adapter tetap tunduk pada context resmi CTS",
  "",
  "## 18. Goal Breakdown",
  "",
  "### 18.1 Goal Utama",
  "",
  "Goal utama roadmap ini adalah:",
  "",
  "- membuat FE siap tumbuh menjadi service-aware frontend",
  "- membuat deploy FE bisa dipindah endpoint tanpa rebuild",
  "- membuat shell governance dan shell operasional jelas boundary-nya",
  "- membuat adapter punya workspace yang kokoh",
  "- menyiapkan place holder resmi untuk licensing dan protection",
  "",
  "### 18.2 Goal per Fase",
  "",
  "`Goal A - Foundation Stability`",
  "",
  "- context binding tunggal",
  "- route ownership jelas",
  "- service ownership jelas",
  "- tidak ada hardcoded host/port di layer UI",
  "",
  "`Goal B - Service Encapsulation`",
  "",
  "- semua API call masuk lewat logical client yang benar",
  "- runtime config menjadi sumber base URL",
  "- auth, CTS, connector, adapter, monitoring punya boundary yang tegas",
  "",
  "`Goal C - Adapter Formalization`",
  "",
  "- adapter tidak lagi jadi tab campuran",
  "- provider mendapat alur teknis yang runtut",
  "- status blocked vs empty vs failed bisa dibedakan",
  "",
  "`Goal D - Bootstrap and License Readiness`",
  "",
  "- app bisa di-lock sebelum fully initialized",
  "- endpoint service bisa diganti dari runtime config",
  "- lisensi bisa menghidupkan atau mematikan capability tertentu",
  "",
  "`Goal E - Progressive Future Split`",
  "",
  "- ketika backend dipecah, FE tidak perlu refactor besar",
  "- ketika modul dijual per paket, feature gating sudah siap",
  "- ketika deployment dipindah, bootstrap tetap jadi gerbang stabil",
  "",
  "### 18.3 Goal per Layer",
  "",
  "| Layer | Goal |",
  "|---|---|",
  "| UI App Layer | portal jelas, tidak campur concern |",
  "| Frontend Service Layer | API abstraction rapi dan mudah dipindah |",
  "| Bootstrap Runtime Layer | init aman, config dinamis, service route stabil |",
  "| License Layer | activation, validation, gating, revalidation |",
  "",
  "## 19. Step-by-Step Development Plan",
  "",
  "### 19.1 Step 1 - Runtime Config Loader",
  "",
  "Deliverable:",
  "",
  "- loader runtime config sebelum render app",
  "- logical service registry",
  "- fallback handling kalau config belum valid",
  "",
  "Hasil yang diharapkan:",
  "",
  "- UI tidak lagi hardcode endpoint final",
  "- environment switch bisa dilakukan dari config",
  "",
  "### 19.2 Step 2 - Logical Client Separation",
  "",
  "Deliverable:",
  "",
  "- `authClient`",
  "- `ctsClient`",
  "- `connectorClient`",
  "- `adapterClient`",
  "- `monitoringClient`",
  "",
  "Hasil yang diharapkan:",
  "",
  "- service ownership mulai tegas",
  "- retry/interceptor bisa dipisah",
  "",
  "### 19.3 Step 3 - API Ownership Audit",
  "",
  "Deliverable:",
  "",
  "- audit semua file `src/api/services/*`",
  "- tandai endpoint family per service",
  "- rapikan service yang masih campur",
  "",
  "Hasil yang diharapkan:",
  "",
  "- mapping FE -> service -> endpoint menjadi konsisten",
  "",
  "### 19.4 Step 4 - Session and Context Hardening",
  "",
  "Deliverable:",
  "",
  "- session resolver tunggal",
  "- active organization resolver",
  "- participant resolver",
  "- domain binding resolver",
  "",
  "Hasil yang diharapkan:",
  "",
  "- provider tidak lagi gampang nyasar ke context salah",
  "",
  "### 19.5 Step 5 - Shell Split",
  "",
  "Deliverable:",
  "",
  "- `CTS Portal Shell`",
  "- `Connector Portal Shell`",
  "- route group terpisah",
  "- menu group terpisah",
  "",
  "Hasil yang diharapkan:",
  "",
  "- governance dan operation tidak lagi saling menumpuk",
  "",
  "### 19.6 Step 6 - Adapter Workspace Formal",
  "",
  "Deliverable:",
  "",
  "- connection registry",
  "- source explorer",
  "- validation task runner",
  "- task monitor",
  "- validated results",
  "- publish handoff",
  "",
  "Hasil yang diharapkan:",
  "",
  "- adapter terlihat sebagai workflow utuh, bukan tempelan",
  "",
  "### 19.7 Step 7 - Bootstrap Gate",
  "",
  "Deliverable:",
  "",
  "- setup status check",
  "- app lock saat config belum siap",
  "- health summary awal",
  "",
  "Hasil yang diharapkan:",
  "",
  "- app tidak langsung tembak request ketika konfigurasi belum valid",
  "",
  "### 19.8 Step 8 - License Validation Integration",
  "",
  "Deliverable:",
  "",
  "- license input di first-run / admin config",
  "- license state storage",
  "- revalidate flow",
  "- feature gating",
  "",
  "Hasil yang diharapkan:",
  "",
  "- instance bisa dikontrol capability-nya tanpa rebuild",
  "",
  "### 19.9 Step 9 - QA and Regression Hardening",
  "",
  "Deliverable:",
  "",
  "- smoke test bootstrap",
  "- smoke test login context",
  "- smoke test adapter workspace",
  "- smoke test transfer center",
  "- validator untuk config invalid / expired license",
  "",
  "Hasil yang diharapkan:",
  "",
  "- perubahan arsitektur tidak merusak flow existing",
  "",
  "## 20. Timeline dan Estimasi",
  "",
  "### 20.1 Estimasi Garis Besar",
  "",
  "Estimasi ini untuk FE side dengan asumsi pengembangan bertahap dan tidak menghitung refactor backend besar.",
  "",
  "| Fase | Fokus | Estimasi |",
  "|---|---|---|",
  "| Phase 1 | runtime config + logical client skeleton | 3 hari |",
  "| Phase 2 | audit API ownership + cleanup service | 3 hari |",
  "| Phase 3 | session/context hardening | 3 hari |",
  "| Phase 4 | shell split CTS vs Connector | 4 sampai 5 hari |",
  "| Phase 5 | adapter workspace formalization | 4 hari |",
  "| Phase 6 | bootstrap gate + first-run control | 2 sampai 3 hari |",
  "| Phase 7 | license integration stub + gating | 3 hari |",
  "| Phase 8 | QA, regression, doc hardening | 2 sampai 3 hari |",
  "",
  "Estimasi total:",
  "",
  "- **24 sampai 27 hari kerja FE**",
  "",
  "### 20.2 Timeline Realistis",
  "",
  "`Sprint 1`",
  "",
  "- runtime config loader",
  "- logical client separation",
  "- API ownership audit",
  "",
  "`Sprint 2`",
  "",
  "- session/context hardening",
  "- shell split",
  "",
  "`Sprint 3`",
  "",
  "- adapter workspace formal",
  "- bootstrap gate",
  "",
  "`Sprint 4`",
  "",
  "- license stub",
  "- feature gating",
  "- QA/regression",
  "",
  "### 20.3 Timeline Cepat vs Aman",
  "",
  "| Mode | Estimasi | Catatan |",
  "|---|---|---|",
  "| cepat | 15 sampai 18 hari | risiko technical debt lebih tinggi |",
  "| moderat | 24 sampai 27 hari | paling seimbang |",
  "| aman | 30+ hari | cocok bila sambil merapikan test dan boundary penuh |",
  "",
  "## 21. Risk Ratio dan Exposure",
  "",
  "### 21.1 Risk Ratio Utama",
  "",
  "| Risk | Severity | Probability | Impact | Exposure |",
  "|---|---|---|---|---|",
  "| runtime config tidak siap sebelum auth init | tinggi | sedang | sangat tinggi | tinggi |",
  "| service boundary dilanggar lagi oleh module lain | sedang | tinggi | tinggi | tinggi |",
  "| session resolver tetap ambigu | kritikal | sedang | sangat tinggi | sangat tinggi |",
  "| adapter context masih ambil fallback lokal | kritikal | tinggi | sangat tinggi | sangat tinggi |",
  "| shell split memicu redirect loop | tinggi | sedang | tinggi | tinggi |",
  "| license gate salah mengunci app | tinggi | rendah | sangat tinggi | sedang |",
  "| feature gating terlalu ditaruh di FE | tinggi | sedang | tinggi | tinggi |",
  "| bootstrap jadi terlalu gemuk dan susah dirawat | sedang | sedang | sedang | sedang |",
  "",
  "### 21.2 Risk Ratio per Fase",
  "",
  "| Fase | Risiko Dominan | Rasio Risiko |",
  "|---|---|---|",
  "| runtime config | app init gagal | 7/10 |",
  "| logical clients | coupling setengah jadi | 5/10 |",
  "| session hardening | user context salah | 9/10 |",
  "| shell split | route guard pecah | 7/10 |",
  "| adapter formalization | provider flow regress | 8/10 |",
  "| bootstrap gate | startup logic macet | 6/10 |",
  "| license integration | false lock / false allow | 8/10 |",
  "",
  "### 21.3 Mitigasi yang Wajib Ada",
  "",
  "- config preload sebelum auth provider mount",
  "- fallback safe mode bila runtime config corrupt",
  "- single source session resolver",
  "- adapter guard berdasarkan participant-domain binding resmi",
  "- feature flags dari bootstrap/license state, bukan hardcoded UI",
  "- health summary page untuk debugging instance",
  "",
  "## 22. End-State yang Dituju",
  "",
  "Kalau roadmap ini selesai, bentuk FE yang dituju adalah:",
  "",
  "- 1 repo yang rapi",
  "- 2 shell yang jelas",
  "- 5 logical clients yang stabil",
  "- adapter workspace yang formal",
  "- bootstrap runtime yang mengunci init",
  "- license-aware deployment bundle",
  "- siap dipindahkan ke banyak environment",
  "- siap berkembang ke standalone services tanpa refactor besar",
  "",
  "Dengan end-state ini:",
  "",
  "- deploy lebih aman",
  "- boundary bisnis lebih jelas",
  "- adapter tidak lagi jadi concern liar",
  "- shell governance dan operasional tidak saling mengganggu",
  "- lisensi dan packaging enterprise bisa masuk dengan wajar",
].join("\\n");

let next = source;
next = next.replace("## 17. Mermaid", `${standaloneSection}\n\n## 23. Mermaid`);
next = next.replace("### 17.1 Shell dan Service", "### 23.1 Shell dan Service");
next = next.replace("### 17.2 Context Resolution", "### 23.2 Context Resolution");
next = next.replace("### 17.3 Adapter Workspace", "### 23.3 Adapter Workspace");

const extraMermaid = `

### 23.4 Standalone Bundle Target

\`\`\`mermaid
flowchart TD
    A[Browser] --> B[Bootstrap Runtime Layer]
    B --> C[Runtime Config Loader]
    B --> D[Setup Status Check]
    B --> E[License Gate]
    B --> F[Logical Service Proxy]

    F --> G[Auth Service]
    F --> H[CTS Service]
    F --> I[Connector Service]
    F --> J[Adapter Service]
    F --> K[Monitoring Service]

    L[UI App Layer] --> M[CTS Portal Shell]
    L --> N[Connector Portal Shell]
    N --> O[Adapter Workspace]
\`\`\`

### 23.5 Development Roadmap

\`\`\`mermaid
flowchart LR
    A[Runtime Config] --> B[Logical Clients]
    B --> C[API Ownership Audit]
    C --> D[Session Hardening]
    D --> E[Shell Split]
    E --> F[Adapter Workspace]
    F --> G[Bootstrap Gate]
    G --> H[License Integration]
    H --> I[QA Hardening]
\`\`\`
`;

next += extraMermaid;

fs.writeFileSync(filePath, next, "utf8");
console.log("Detailed blueprint upgraded with standalone roadmap.");
